// <auto-generated />
using System;
using ClinicSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClinicSystem.Migrations
{
    [DbContext(typeof(SystemClinicContext))]
    partial class SystemClinicContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ClinicSystem.Models.Consulta", b =>
                {
                    b.Property<int>("ConsultaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoMatDescartable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumHistoriaClinica")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NumMatricula")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.HasKey("ConsultaId");

                    b.HasIndex("NumHistoriaClinica");

                    b.HasIndex("NumMatricula");

                    b.HasIndex("TipoId");

                    b.ToTable("Consultas");

                    b.HasData(
                        new
                        {
                            ConsultaId = 1,
                            Active = true,
                            Costo = 1550.50m,
                            CostoMatDescartable = 0m,
                            Descripcion = "Consulta Pediatria",
                            Fecha = new DateTime(2022, 3, 30, 12, 10, 15, 0, DateTimeKind.Unspecified),
                            NumHistoriaClinica = "9876541",
                            NumMatricula = "123456",
                            TipoId = 1
                        },
                        new
                        {
                            ConsultaId = 2,
                            Active = true,
                            Costo = 1550.50m,
                            CostoMatDescartable = 0m,
                            Descripcion = "Consulta Neuro",
                            Fecha = new DateTime(2022, 3, 30, 12, 10, 15, 0, DateTimeKind.Unspecified),
                            NumHistoriaClinica = "9876542",
                            NumMatricula = "123457",
                            TipoId = 1
                        },
                        new
                        {
                            ConsultaId = 3,
                            Active = true,
                            Costo = 1550.50m,
                            CostoMatDescartable = 0m,
                            Descripcion = "Consulta Odonto",
                            Fecha = new DateTime(2022, 3, 30, 12, 10, 15, 0, DateTimeKind.Unspecified),
                            NumHistoriaClinica = "9876543",
                            NumMatricula = "123458",
                            TipoId = 1
                        },
                        new
                        {
                            ConsultaId = 4,
                            Active = true,
                            Costo = 1550.50m,
                            CostoMatDescartable = 0m,
                            Descripcion = "Consulta Oftalmo",
                            Fecha = new DateTime(2022, 3, 30, 12, 10, 15, 0, DateTimeKind.Unspecified),
                            NumHistoriaClinica = "9876544",
                            NumMatricula = "123459",
                            TipoId = 1
                        },
                        new
                        {
                            ConsultaId = 5,
                            Active = true,
                            Costo = 1550.50m,
                            CostoMatDescartable = 1550.50m,
                            Descripcion = "P.M. Pediatria",
                            Fecha = new DateTime(2022, 4, 30, 12, 10, 15, 0, DateTimeKind.Unspecified),
                            NumHistoriaClinica = "9876541",
                            NumMatricula = "123456",
                            TipoId = 2
                        },
                        new
                        {
                            ConsultaId = 6,
                            Active = true,
                            Costo = 1550.50m,
                            CostoMatDescartable = 1550.50m,
                            Descripcion = "P.M. Neuro",
                            Fecha = new DateTime(2022, 4, 30, 12, 10, 15, 0, DateTimeKind.Unspecified),
                            NumHistoriaClinica = "9876542",
                            NumMatricula = "123457",
                            TipoId = 2
                        },
                        new
                        {
                            ConsultaId = 7,
                            Active = true,
                            Costo = 1550.50m,
                            CostoMatDescartable = 1550.50m,
                            Descripcion = "P.M. Odonto",
                            Fecha = new DateTime(2022, 4, 30, 12, 10, 15, 0, DateTimeKind.Unspecified),
                            NumHistoriaClinica = "9876543",
                            NumMatricula = "123458",
                            TipoId = 2
                        },
                        new
                        {
                            ConsultaId = 8,
                            Active = true,
                            Costo = 1550.50m,
                            CostoMatDescartable = 1550.50m,
                            Descripcion = "P.M. Oftalmo",
                            Fecha = new DateTime(2022, 4, 30, 12, 10, 15, 0, DateTimeKind.Unspecified),
                            NumHistoriaClinica = "9876544",
                            NumMatricula = "123459",
                            TipoId = 2
                        });
                });

            modelBuilder.Entity("ClinicSystem.Models.Medico", b =>
                {
                    b.Property<string>("NumMatricula")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Especialidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NumMatricula");

                    b.ToTable("Medicos");

                    b.HasData(
                        new
                        {
                            NumMatricula = "123456",
                            Especialidad = "Pediatria",
                            IsActive = true,
                            Nombre = "Juan Achaval"
                        },
                        new
                        {
                            NumMatricula = "123457",
                            Especialidad = "Neurologia",
                            IsActive = true,
                            Nombre = "Agus Repetto"
                        },
                        new
                        {
                            NumMatricula = "123458",
                            Especialidad = "Odontologia",
                            IsActive = true,
                            Nombre = "Lautaro Diaz"
                        },
                        new
                        {
                            NumMatricula = "123459",
                            Especialidad = "Oftalmologia",
                            IsActive = true,
                            Nombre = "Felipe Gonzales"
                        });
                });

            modelBuilder.Entity("ClinicSystem.Models.Paciente", b =>
                {
                    b.Property<string>("NumHistoriaClinica")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NumHistoriaClinica");

                    b.ToTable("Pacientes");

                    b.HasData(
                        new
                        {
                            NumHistoriaClinica = "9876541",
                            IsActive = true,
                            Nombre = "Humberto Gorosito"
                        },
                        new
                        {
                            NumHistoriaClinica = "9876542",
                            IsActive = true,
                            Nombre = "Gustavo Gustavino"
                        },
                        new
                        {
                            NumHistoriaClinica = "9876543",
                            IsActive = true,
                            Nombre = "Hernando Hernandez"
                        },
                        new
                        {
                            NumHistoriaClinica = "9876544",
                            IsActive = true,
                            Nombre = "Diego Torrado"
                        },
                        new
                        {
                            NumHistoriaClinica = "9876545",
                            IsActive = true,
                            Nombre = "Facundo Niembro"
                        });
                });

            modelBuilder.Entity("ClinicSystem.Models.Tipo", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoId");

                    b.ToTable("Tipos");

                    b.HasData(
                        new
                        {
                            TipoId = 1,
                            Descripcion = "Consultorio"
                        },
                        new
                        {
                            TipoId = 2,
                            Descripcion = "Practica Medica"
                        });
                });

            modelBuilder.Entity("ClinicSystem.Models.Consulta", b =>
                {
                    b.HasOne("ClinicSystem.Models.Paciente", "Paciente")
                        .WithMany("Consultas")
                        .HasForeignKey("NumHistoriaClinica");

                    b.HasOne("ClinicSystem.Models.Medico", "Medico")
                        .WithMany("Consultas")
                        .HasForeignKey("NumMatricula");

                    b.HasOne("ClinicSystem.Models.Tipo", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Paciente");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("ClinicSystem.Models.Medico", b =>
                {
                    b.Navigation("Consultas");
                });

            modelBuilder.Entity("ClinicSystem.Models.Paciente", b =>
                {
                    b.Navigation("Consultas");
                });
#pragma warning restore 612, 618
        }
    }
}
